import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const salesDataSeed = [
  {
    transactionId: "1234567",
    date: new Date("2023-09-26"),
    customerId: "CUST12016",
    customerName: "Neha Yadav",
    phoneNumber: "+91 9123456789",
    gender: "Female",
    age: 25,
    customerRegion: "South",
    productCategory: "Clothing",
    productId: "PROD0001",
    employeeName: "Harsh Agrawal",
    tags: ["Premium", "New Arrival"],
    quantity: 5,
    pricePerUnit: 200,
    discountPercentage: 0,
    totalAmount: 1000,
    finalAmount: 1000,
    paymentMethod: "Credit Card",
  },
  {
    transactionId: "1234568",
    date: new Date("2023-09-26"),
    customerId: "CUST12017",
    customerName: "Amit Sharma",
    phoneNumber: "+91 9876543210",
    gender: "Male",
    age: 32,
    customerRegion: "South",
    productCategory: "Electronics",
    productId: "PROD0002",
    employeeName: "Rajesh Kumar",
    tags: ["Best Seller"],
    quantity: 2,
    pricePerUnit: 15000,
    discountPercentage: 5,
    totalAmount: 30000,
    finalAmount: 28500,
    paymentMethod: "UPI",
  },
  {
    transactionId: "1234569",
    date: new Date("2023-09-25"),
    customerId: "CUST12018",
    customerName: "Priya Singh",
    phoneNumber: "+91 9988776655",
    gender: "Female",
    age: 28,
    customerRegion: "East",
    productCategory: "Footwear",
    productId: "PROD0003",
    employeeName: "Priya Sharma",
    tags: ["Discounted"],
    quantity: 1,
    pricePerUnit: 3500,
    discountPercentage: 15,
    totalAmount: 3500,
    finalAmount: 2975,
    paymentMethod: "Debit Card",
  },
  {
    transactionId: "1234570",
    date: new Date("2023-09-25"),
    customerId: "CUST12019",
    customerName: "Rahul Verma",
    phoneNumber: "+91 9112233445",
    gender: "Male",
    age: 45,
    customerRegion: "West",
    productCategory: "Accessories",
    productId: "PROD0004",
    employeeName: "Amit Patel",
    tags: ["Limited Edition"],
    quantity: 3,
    pricePerUnit: 2000,
    discountPercentage: 0,
    totalAmount: 6000,
    finalAmount: 6000,
    paymentMethod: "Cash",
  },
  {
    transactionId: "1234571",
    date: new Date("2023-09-24"),
    customerId: "CUST12020",
    customerName: "Anjali Gupta",
    phoneNumber: "+91 9556677889",
    gender: "Female",
    age: 35,
    customerRegion: "North",
    productCategory: "Electronics",
    productId: "PROD0005",
    employeeName: "Neha Singh",
    tags: ["New Arrival"],
    quantity: 1,
    pricePerUnit: 25000,
    discountPercentage: 20,
    totalAmount: 25000,
    finalAmount: 20000,
    paymentMethod: "Credit Card",
  },
  {
    transactionId: "1234572",
    date: new Date("2023-09-23"),
    customerId: "CUST12021",
    customerName: "Vikram Desai",
    phoneNumber: "+91 9334455667",
    gender: "Male",
    age: 50,
    customerRegion: "South",
    productCategory: "Clothing",
    productId: "PROD0006",
    employeeName: "Rohit Malhotra",
    tags: ["Premium"],
    quantity: 2,
    pricePerUnit: 4500,
    discountPercentage: 8,
    totalAmount: 9000,
    finalAmount: 8280,
    paymentMethod: "Debit Card",
  },
  {
    transactionId: "1234573",
    date: new Date("2023-09-22"),
    customerId: "CUST12022",
    customerName: "Sneha Iyer",
    phoneNumber: "+91 9778899001",
    gender: "Female",
    age: 23,
    customerRegion: "East",
    productCategory: "Footwear",
    productId: "PROD0007",
    employeeName: "Anita Desai",
    tags: ["Best Seller", "New Arrival"],
    quantity: 1,
    pricePerUnit: 2500,
    discountPercentage: 5,
    totalAmount: 2500,
    finalAmount: 2375,
    paymentMethod: "UPI",
  },
  {
    transactionId: "1234574",
    date: new Date("2023-09-21"),
    customerId: "CUST12023",
    customerName: "Arjun Nair",
    phoneNumber: "+91 9223344556",
    gender: "Male",
    age: 38,
    customerRegion: "West",
    productCategory: "Accessories",
    productId: "PROD0008",
    employeeName: "Vikram Reddy",
    tags: ["Discounted"],
    quantity: 4,
    pricePerUnit: 1500,
    discountPercentage: 10,
    totalAmount: 6000,
    finalAmount: 5400,
    paymentMethod: "Credit Card",
  },
  {
    transactionId: "1234575",
    date: new Date("2023-09-20"),
    customerId: "CUST12024",
    customerName: "Divya Patel",
    phoneNumber: "+91 9001122334",
    gender: "Female",
    age: 29,
    customerRegion: "North",
    productCategory: "Electronics",
    productId: "PROD0009",
    employeeName: "Sanjay Gupta",
    tags: ["Premium", "Limited Edition"],
    quantity: 1,
    pricePerUnit: 35000,
    discountPercentage: 15,
    totalAmount: 35000,
    finalAmount: 29750,
    paymentMethod: "Cash",
  },
  {
    transactionId: "1234576",
    date: new Date("2023-09-19"),
    customerId: "CUST12025",
    customerName: "Rohan Kapoor",
    phoneNumber: "+91 9445566778",
    gender: "Male",
    age: 42,
    customerRegion: "South",
    productCategory: "Clothing",
    productId: "PROD0010",
    employeeName: "Meera Joshi",
    tags: ["New Arrival"],
    quantity: 3,
    pricePerUnit: 3500,
    discountPercentage: 12,
    totalAmount: 10500,
    finalAmount: 9240,
    paymentMethod: "Debit Card",
  },
  {
    transactionId: "1234577",
    date: new Date("2023-09-18"),
    customerId: "CUST12026",
    customerName: "Pooja Reddy",
    phoneNumber: "+91 9667788990",
    gender: "Female",
    age: 31,
    customerRegion: "East",
    productCategory: "Footwear",
    productId: "PROD0011",
    employeeName: "Arun Nair",
    tags: ["Best Seller"],
    quantity: 2,
    pricePerUnit: 4000,
    discountPercentage: 0,
    totalAmount: 8000,
    finalAmount: 8000,
    paymentMethod: "UPI",
  },
  {
    transactionId: "1234578",
    date: new Date("2023-09-17"),
    customerId: "CUST12027",
    customerName: "Nikhil Joshi",
    phoneNumber: "+91 9889900112",
    gender: "Male",
    age: 26,
    customerRegion: "West",
    productCategory: "Electronics",
    productId: "PROD0012",
    employeeName: "Kavita Menon",
    tags: ["Discounted"],
    quantity: 1,
    pricePerUnit: 12000,
    discountPercentage: 25,
    totalAmount: 12000,
    finalAmount: 9000,
    paymentMethod: "Credit Card",
  },
  {
    transactionId: "1234579",
    date: new Date("2023-09-16"),
    customerId: "CUST12028",
    customerName: "Megha Bhat",
    phoneNumber: "+91 9001223445",
    gender: "Female",
    age: 27,
    customerRegion: "North",
    productCategory: "Accessories",
    productId: "PROD0013",
    employeeName: "Deepak Verma",
    tags: ["Premium", "New Arrival"],
    quantity: 2,
    pricePerUnit: 2500,
    discountPercentage: 5,
    totalAmount: 5000,
    finalAmount: 4750,
    paymentMethod: "Debit Card",
  },
  {
    transactionId: "1234580",
    date: new Date("2023-09-15"),
    customerId: "CUST12029",
    customerName: "Sanjay Malik",
    phoneNumber: "+91 9223334445",
    gender: "Male",
    age: 48,
    customerRegion: "South",
    productCategory: "Clothing",
    productId: "PROD0014",
    employeeName: "Sunita Rao",
    tags: ["Limited Edition"],
    quantity: 1,
    pricePerUnit: 6000,
    discountPercentage: 10,
    totalAmount: 6000,
    finalAmount: 5400,
    paymentMethod: "Cash",
  },
  {
    transactionId: "1234581",
    date: new Date("2023-09-14"),
    customerId: "CUST12030",
    customerName: "Kavya Singh",
    phoneNumber: "+91 9445556667",
    gender: "Female",
    age: 24,
    customerRegion: "East",
    productCategory: "Footwear",
    productId: "PROD0015",
    employeeName: "Manish Kapoor",
    tags: ["New Arrival"],
    quantity: 1,
    pricePerUnit: 3000,
    discountPercentage: 7,
    totalAmount: 3000,
    finalAmount: 2790,
    paymentMethod: "UPI",
  },
];

async function main() {
  console.log("Starting database seed...");

  // Clear existing records
  await prisma.salesRecord.deleteMany({});

  // Seed records
  for (const record of salesDataSeed) {
    await prisma.salesRecord.create({
      data: record,
    });
  }

  console.log("Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
